config/routes.rb
Rails.application.routes.draw do
 root "count#index"
 resources :users, :except => [:destroy]
 get 'login', to: 'users#login_form'
 get '/logout' => "users#logout"
 post 'login', to: 'users#login'

 resources 'count', only: :index do
  collection { post :import}
 end
 
 post "/count/call_outbound/:id/update" => "count#update_c_o"
 get "/count/call_outbound/:id" => "count#c_o"
 get "/upload" => "count#upload"
 get "/count/:date" => "count#getdate"
 get "/count/user/:op_name" => "count#op_name"
 get '/ser' => "count#ser"
 post "/del" => "count#del"
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/count.rb
class Count < ApplicationRecord
	 require "date"

  def self.import(file)
    int = 0 
    @place_key = "東京CS"
    CSV.foreach(file) do |row|
      int += 1
      if int == 1
        @place = row[1]
      end
      if @place != @place_key
        redirect_to "/import"
      end
      if int == 2
        @about_date = row[1].to_date
      end
      if int >= 6 && row[1].to_i != 0
      count = Count.new   
      count.name = row[0]
      count.total_call  = row[1].to_i 
      count.av_acd = row[2].to_i
      count.total_op_time = row[1].to_i * row[2].to_i
      count.av_pp = row[3].to_i
      count.date = @about_date.strftime("%Y%m%d")   
      count.save
      end
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
	validates :u_name, {presence: true, uniqueness: true}
	validates :login_id, {presence: true, uniqueness: true}
	has_secure_password
	validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
# アクション追加
  before_action :set_current_user
  
  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end
  
  def not_login_user
    if @current_user == nil
      redirect_to login_path, notice: "ログインしてください"
    end
  end
  
  def already_login
    if @current_user
      redirect_to users_path, notice: "既にログイン済みです"
    end
  end

# end

end

app/controllers/count_controller.rb
class CountController < ApplicationController
before_action :not_login_user, {only: [:import, :del, :upload]}
helper_method :sort_column, :sort_direction
  
  require "date"
  def index
    @max_new = Count.maximum('date')
    if @max_new
    @new_date = Count.where(:date => @max_new).order(sort_column + ' ' + sort_direction)
    @yesterday = @max_new.yesterday
    @tomorrow = @max_new.tomorrow

    @yes = @yesterday.strftime("%Y-%m-%d")
    @tom = @tomorrow.strftime("%Y-%m-%d")
    end
  end
  
  def import
    if params[:file]
  	 Count.import(params[:file].path)
      redirect_to root_path, notice: "CSVのインポートが完了しました"
    elsif !params[:tsv].blank?
      tsv_to_csv = params[:tsv].chomp.split("\t").join(",")
      File.open("public/tsv.csv","w") { |file| file.print(tsv_to_csv) }
      Count.import("public/tsv.csv")
      FileUtils.rm("public/tsv.csv")
      redirect_to root_path, notice: "テキストのインポートが完了しました"
    else
       redirect_to upload_path, alert: "ファイル、またはテキストが空です"
    end
    rescue
      redirect_to upload_path, alert: "ファイル形式、またはテキスト形式が正しくありません"
  end

  def getdate
    @date = Count.where(date: Date.parse(params[:date])).order(sort_column + ' ' + sort_direction)
    @today = Date.parse(params[:date])
    @yesterday = @today.yesterday
    @tomorrow = @today.tomorrow
    
    @yes = @yesterday.strftime("%Y-%m-%d") 
    @tom = @tomorrow.strftime("%Y-%m-%d")
  end
  def del
    destroy_at = Count.where(date: Date.parse(params[:date]))
    destroy_at.destroy_all
    redirect_to root_path, notice: "対象の日付のデータを削除しました" 
  end
  
  def upload
  end


# ソート
private
  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
  end
 
  def sort_column
      Count.column_names.include?(params[:sort]) ? params[:sort] : "total_call"
  end

  def sort_direction_op
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "desc"
  end
 
  def sort_column_op
      Count.column_names.include?(params[:sort]) ? params[:sort] : "date"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # @current_userのIDと、URL（pramsの）IDが異なる場合
  before_action :not_login_user, {only: [:index, :show, :edit, :update, :new, :create]}
  # 既にログイン済みの場合
  before_action :already_login, {only: [:login_form, :login]}
  # before_actionで別ユーザーの編集の制限 edit,update
  before_action :not_this_user, {only: [:edit, :update]}

# 管理者系処理
  # 管理者一覧
  def index
  	@users = User.all
  end
  # 管理者個別ページ
  def show
  	@user = User.find_by(id: params[:id])
  end
  # 新規管理者登録ページ
  def new
  	@user = User.new
  end
  # 管理者登録
  def create
    @user = User.new(user_params)
  	@user.user_image = "default.jpg"
  	if @user.save
  		redirect_to users_path, notice: "ユーザー登録が完了しました"
  	else
  		render("users/new")
  	end
  end
  # before_actionで別ユーザーの編集の制限 edit,update
  def not_this_user
    if @current_user.id != params[:id].to_i
      redirect_to users_path, notice: "自分ではないユーザーのため編集する権限がありません"
    end
  end
  # ユーザー編集 editページとupdate処理
  def edit
    @user = User.find_by(id: params[:id])
  end
  def update
    @user = User.find_by(id: params[:id])
    if @user.update(user_params)
          if user_params[:user_image]
            @user.user_image = "#{@user.id}.jpg"
            image = user_params[:user_image]
            File.binwrite("public/user_images/#{@user.user_image}", image.read)
            @user.save
          end
      redirect_to users_path, notice: "ユーザー情報を編集しました"
    else
      render("users/edit")
    end
  end

# ログイン系の処理
  # フォーム表示
  def login_form
  end
  # ログイン処理
  def login
    @user = User.find_by(login_id: login_params[:login_id])
    if @user && @user.authenticate(login_params[:password])
      session[:user_id] = @user.id
      redirect_to users_path, notice: "ログインしました"
    else
      @error_message = "ログインIDまたはパスワードが間違っています"
      @login_id = params[:login_id]
      @password = params[:password]
      render("users/login_form")
    end
  end
  # ログアウト処理
  def logout
    reset_session
    redirect_to login_path, notice: "ログアウトしました"
  end
  
  #パラメータ系
  private
  def user_params
    params.require(:user).permit(:u_name, :login_id, :password, 
    :password_confirmation, :user_image)
  end
  def login_params
    params.require(:user).permit(:login_id, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end
end

app/helpers/count_helper.rb
module CountHelper
# 	def from_root(path)
#   		ENV["RAILS_RELATIVE_URL_ROOT"] + path
# 	end
end

app/helpers/users_helper.rb
module UsersHelper
# 	def from_root(path)
#   		ENV["RAILS_RELATIVE_URL_ROOT"] + path
# 	end
end

app/views/count/c_o.html.erb
<br>
<% if @data %>
<div class="text-center"><h3><%= @data.name %>さんの架電・メール対応件数編集</h3>
<br>
<div class="card mx-auto" style="width: 30rem">
  <div class="card-header">架電・メール対応件数編集</div>
  <div class="card-body mx-auto text-center">
    <h5 class="card-title text-center"><%= @data.date %>を件数を編集</h5>
    <%= form_tag ("/count/call_outbound/#{@data.id}/update") do %>
    架電件数<br>
    <input type="text" size="3" name="outbound" value="<%= @data.outbound %>"><br><br>
    メール対応件数<br>
    <input type="text" size="3" name="mail" value="<%= @data.mail %>"><br><br>
    <%= submit_tag "保存",:class => "btn btn-danger" %><br>
    <% end %>
  </div>
</div>
<br>
<a href="<%= root_path %>"><button type="button" class="btn btn-info">一覧に戻る</button></a>
</div>
<br>
<% end %>

app/views/count/getdate.html.erb
<br>  
<div class="text-center"><h3><%= @today %>の対応件数</h3><br>


<a href="<%= "/count/#{@yes}" %>"><button type="button" class="btn btn-info">前日</button></a>
<a href="<%= root_path %>"><button type="button" class="btn btn-dark">最新の対応件数</button></a>
<a href="<%= "/count/#{@tom}" %>" style="text-align: right">
<button type="button" class="btn btn-info">翌日</button></a>
</div>
<br>
<!--<div class="container text-center">-->
<!--<%= form_tag "/ser", {method: :get} do %>-->
<!--  <div class="input-group mx-auto" style="width: 17rem">-->

<!--  <%= date_select :ser_date, :date_select, :use_two_digit_numbers => true %>-->
  
<!--  <button class="btn btn-outline-info" type="submit">対象日を検索</button>-->
<!--  </div>-->
<!--<% end %>-->
<!--</div>-->


   <div class="container" style="width: 35rem; font-size: 50%">
        <table class="table table-bordered text-center">
          <thead class="thead-dark">
            <tr>
              
              <th scope="col">名前</th>
              <!--<th scope="col">架電件数</th>-->
              <th scope="col"><%= sortable "total_call", "受電合計" %></th>
              <th scope="col" style="width: 6rem"><%= sortable "total_op_time", "合計対応時間" %></th>
              <th scope="col"><%= sortable "av_acd", "平均対応時間" %></th>
              <th scope="col"><%= sortable "av_pp", "平均後処理時間" %></th>
              <!--<th scope="col">メール件数</th>-->
              <!--<th scope="col">架電・メール編集</th>-->
              <th scope="col">対象日</th>
            </tr>
          </thead>

          <tbody>
            <% @date.each do |count| %>
            <% total_fun = count.total_op_time/60 %>
              <tr>
                
                <td><%= count.name %></td>
                <!--<td><%= count.outbound %>件</td>-->
                <td><%= count.total_call %>件</td>
                <td><%= count.total_op_time %>秒 (<%= total_fun %>分)</td>
                <td><%= count.av_acd.floor %>秒</td>
                <td><%= count.av_pp.floor %>秒</td>
                <!--<td><%= count.mail %>件</td>-->
                <td><%= count.date %></td>
                <!--<td><%= link_to "編集", "http://hostingwiki.internal-gmo/avaya/count/call_outbound/#{count.id}" %></td>-->
            <% end %>
          </tbody>
        </table>
          <% if @current_user  %>
             <div class="text-right">
             <%= form_tag "/del" do %>
             <%= hidden_field_tag :date, @today %>     

             <%= submit_tag "この日付のデータを削除" ,data: {confirm: "本当に削除してもいいですか？"},:class => "btn btn-danger" %>
             <% end %></div>
          <% end %>
    </div>

   </div> 
   <br><br>

app/views/count/index.html.erb
<br>
<% if @new_date %>
<div class="text-center"><h3><%= @max_new %>の対応件数</h3><br>



<a href="<%= "/count/#{@yes}" %>"><button type="button" class="btn btn-info" >前日</button></a>
<a href="<%= root_path %>"><button type="button" class="btn btn-dark" >最新の対応件数</button></a>
<a href="<%= "/count/#{@tom}" %>"><button type="button" class="btn btn-info" >翌日</button></a>
</div>
<br>
   <div class="container" style="width: 35rem; font-size: 50%">
        <table class="table table-bordered text-center">
          <thead class="thead-dark">
            <tr>
              <th scope="col">名前</th>
              <th scope="col"><%= sortable "total_call", "受電合計" %></th>
              <th scope="col" style="width: 6rem"><%= sortable "total_op_time", "合計対応時間" %></th>
              <th scope="col"><%= sortable "av_acd", "平均対応時間" %></th>
              <th scope="col"><%= sortable "av_pp", "平均後処理時間" %></th>
              <th scope="col">対象日</th>
            </tr>
          </thead>

          <tbody>
            <% @new_date.each do |count| %>
            <% total_fun = count.total_op_time/60 %>
              <tr>
                <td><%= count.name %></td>
                <td><%= count.total_call %>件</td>
                <td><%= count.total_op_time %>秒 (<%= total_fun %>分)</td>
                <td><%= count.av_acd.floor %>秒</td>
                <td><%= count.av_pp.floor %>秒</td>
                 <td><%= count.date %></td>
            <% end %>
          </tbody>
        </table>
          <% if @current_user  %>
             <div class="text-right">
             <%= form_tag "/del" do %>
             <%= hidden_field_tag :date, @max_new %>

             <%= submit_tag "この日付のデータを削除" ,data: {confirm: "本当に削除してもいいですか？"},:class => "btn btn-danger" %>
             <% end %></div>
          <% end %>
    </div>
    </div>

   </div>
<br><br>
<% else %>
<div class="card mx-auto" style="width: 50%">
  <div class="card-header">
    ！データがありません
  </div>
  <div class="card-body" >
    <h2 class="card-title">まだデータが登録されておりません</h2>
    <p class="card-text">通常は、こちらのページにて、最新の対応件数が表示されます。<br>管理者ログインの上、メニューの【CSVアップロード】よりデータをインポートしてください。</p>
  </div>
</div>
<% end %>

app/views/count/op_name.html.erb
<br>
<% if @op_name %>
<div class="text-center"><h3><%= @op_name %>さんの対応件数一覧</h3>
<a href="<%= root_path %>"><button type="button" class="btn btn-info">一覧に戻る</button></a>



</div>
<br>



<br>
   <div class="container" style="width: 42rem; font-size: 50%">
        <table class="table table-bordered text-center">
          <thead class="thead-dark">
            <tr>
              <th scope="col"><%= sortable "date", "対象日" %></th>
              <th scope="col">名前</th>
              <th scope="col">架電件数</th>
              <th scope="col"><%= sortable "total_call", "受電合計" %></th>
              <th scope="col" style="width: 6rem"><%= sortable "total_op_time", "合計対応時間" %></th>
              <th scope="col"><%= sortable "av_acd", "平均対応時間" %></th>
              <th scope="col"><%= sortable "av_pp", "平均後処理時間" %></th>
              <th scope="col">メール件数</th>
            </tr>
          </thead>

          <tbody>
            <% @op_data.each do |count| %>
            <% total_fun = count.total_op_time/60 %>
              <tr>
                <td><%= count.date %></td>
                <td><%= count.name %></td>
                <td><%= count.outbound %>件</td>
                <td><%= count.total_call %>件</td>
                <td><%= count.total_op_time %>秒 (<%= total_fun %>分)</td>
                <td><%= count.av_acd.floor %>秒</td>
                <td><%= count.av_pp.floor %>秒</td>
                <td><%= count.mail %>件</td>
                 
            <% end %>
          </tbody>
        </table>
          
    </div>

   </div>
<br><br>
<% else %>
<div class="card mx-auto" style="width: 50%">
  <div class="card-header">
    ！データがありません
  </div>
  <div class="card-body" >
    <h2 class="card-title">まだデータが1件も登録されておりません</h2>
    <p class="card-text">通常は、こちらのページにて、最新の対応件数が表示されます。<br>メニューの【CSVアップロード】よりデータをインポートしてください。</p>
  </div>
</div>
<% end %>

app/views/count/upload.html.erb
<br>
<br>

<div class="card mx-auto" style="width: 25rem;">
  <div class="card-header border-info"> CSVアップロード</div>
   
  <div class="card-body">
    <h4 class="card-title" style="color: white">CSVアップロードフォーム</h4>
    <p class="card-text">CSVを選択してインポートボタンをおしてください</p>
    <%= form_tag import_count_index_path, multipart: true do %>
    <%= file_field_tag :file,:class => "btn btn-outline-info" %>
    <br><br>
    <%= submit_tag "インポート",:class => "btn btn-info" %>
    <% end %>
  </div>
</div>
<br>

<div class="card mx-auto" style="width: 76%">
  <div class="card-header border-info"> テキストアップロード </div>
  <div class="card-body">
    <h4 class="card-title" style="color: white">テキストアップロードフォーム</h4>
    <p class="card-text">タブ区切りのAvayaのデータをペーストしてインポートボタンをおしてください</p>
    <%= form_tag import_count_index_path do %>
    <textarea name="tsv" id="" cols="150" rows="10" style="font-size: 50%"></textarea>
    <br><br>
    <%= submit_tag "インポート",:class => "btn btn-info" %>
    <% end %>
  </div>
</div>
<br><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AvayaCSV</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
 <body>
<!--navbarここから-->
  <nav class="navbar navbar-expand navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>">AvayaCSV</a>
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav">
      <% if @current_user  %>
          <li class="nav-item">
             <a class="nav-link" href="<%= "/users/#{@current_user.id}" %>">
            <img src="<%= "/user_images/#{@current_user.user_image}" %>" class="rounded-circle" style="margin-right:10px; width: 30px; height: 30px">
             <span class="text-warning"><%= @current_user.u_name %></span><span>さんとしてログイン中</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= upload_path %>" ><%= fa_icon 'cloud-upload fa-lg' %> CSVアップロード</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= users_path %>"><%= fa_icon 'users fa-lg' %> 管理者一覧</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= new_user_path %>"><%= fa_icon 'user-plus fa-lg' %> 管理者追加</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= logout_path %>"><%= fa_icon 'sign-out fa-lg' %> ログアウト</a>
            
          </li>
      <% else %>
          <li class="nav-item">
            <a class="nav-link" href="<%= login_path %>"><%= fa_icon 'sign-in fa-lg' %> 管理者ログイン</a>
          </li>
      <% end %>
    </ul>
  </div>
</nav>
<!--navbarここまで-->

<!--notice,alert表示-->
    <% if flash[:notice] %>
      <div class="flash">
        <div class="alert alert-warning" role="alert">
        <%= flash[:notice] %>
        </div>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="flash">
        <div class="alert alert-danger" role="alert">
        <%= flash[:alert] %>
        </div>
      </div>
    <% end %>
<!--notice,alert表示ここまで-->

    <%= yield %>
    <footer>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<br><br>
      <!-- バリデーションエラーを表示 -->
      <% if @user.errors.any? %>
            <% @user.errors.full_messages.each do |message| %>
              <p class="text-danger" style="text-align: center"><%= message %></p>
            <% end %>
      <% end %>
      <!-- バリデーションエラーを表示　ここまで -->
<div class="card mx-auto" style="width: 30rem">
  <div class="card-header">ユーザー編集</div>
  <div class="card-body mx-auto text-center">
    <h5 class="card-title text-center">ユーザー編集</h5>

    <%= form_with model: @user, local: true, multipart: true do |f| %>
    <%= f.label :u_name, "名前" %>
    <%= f.text_field :u_name, class: 'form-control' %>
    <%= f.label :login_id, "ログインID" %>
    <%= f.text_field :login_id, class: 'form-control' %>
    <%= f.label :password, "パスワード" %>
    <%= f.password_field :password, class: 'form-control' %>
    <%= f.label :password_confirmation, "パスワード確認" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %><br>
    <%= f.label :user_image, "※画像を変更する場合は、画像を選択してください" %>
    <%= f.file_field :user_image, class: 'form-control' %>
    <%= f.submit '編集', class: 'btn btn-info form-control' %>
    <% end %>
    
  </div>
</div>
<br><br><br><br>

app/views/users/index.html.erb
<br><br>
<p class="h2 text-center text-info">管理者一覧</p>
<br>
<ul class="list-group mx-auto" style="width: 30rem">
<% @users.each do |user| %>
    <li class="list-group-item">
      <img src="<%= "/user_images/#{user.user_image}" %>" class="rounded-circle" style="margin-right:20px; width: 60px; height: 60px"><%= link_to user.u_name, user_path(user) %>
    </li>
  <% end %>
</ul>

app/views/users/login_form.html.erb
<br><br>
<p class="text-danger" style="text-align: center"><%= @error_message %></p>
  
<div class="card mx-auto" style="width: 20rem">
  <div class="card-header">
    管理者ログイン
  </div>
  <div class="card-body mx-auto text-center">
    <h5 class="card-title text-center">ログインフォーム</h5>
  
    <%= form_with scope: :user, local: true do |f| %>
    <%= f.label :login_id, "ログインID" %>
    <%= f.text_field :login_id, class: 'form-control' %>
    <%= f.label :password, "パスワード" %>
    <%= f.password_field :password, class: 'form-control' %><br>
    <%= f.submit 'ログイン', class: 'btn btn-info form-control' %>

    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<br><br>
      <!-- バリデーションエラーを表示 -->
      <% if @user.errors.any? %>
            <% @user.errors.full_messages.each do |message| %>
              <p class="text-danger" style="text-align: center"><%= message %></p>
            <% end %>
      <% end %>
      <!-- バリデーションエラーを表示　ここまで -->
<div class="card mx-auto" style="width: 30rem">
  <div class="card-header">管理者追加</div>
  <div class="card-body mx-auto text-center">
    <h5 class="card-title text-center">管理者追加フォーム</h5>
      
    <%= form_with model: @user, local: true do |f| %>
    <%= f.label :u_name, "名前" %>
    <%= f.text_field :u_name, class: 'form-control' %>
    <%= f.label :login_id, "ログインID" %>
    <%= f.text_field :login_id, class: 'form-control' %>
    <%= f.label :password, "パスワード" %>
    <%= f.password_field :password, class: 'form-control' %>
    <%= f.label :password_confirmation, "パスワード確認" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %><br>
    <%= f.submit '追加', class: 'btn btn-info form-control' %>
    <% end %>

  </div>
</div>
<br><br><br><br>

app/views/users/show.html.erb
<br><br>
<div class="card mx-auto" style="width: 30rem">
  <div class="card-body">
    <h5 class="card-title text-center">ユーザー情報</h5>
    <div class="text-center">
    <img src="<%= "/user_images/#{@user.user_image}" %>" class="rounded-circle" style="margin-right:20px; width: 100px; height: 100px"><br><br>
    <p class="card-text">名前: <%= @user.u_name %></p>
    <p class="card-text">ログインID: <%= @user.login_id %></p>
    </div>
    <br><br>
    <div class="text-center">
    <a href="<%= edit_user_path %>" class="btn btn-info">編集</a>
    </div>
  </div>
</div>